baseURL: https://laurespake.netlify.app/
theme: hugo-apero
locale: en
title: 
author: Laure Spake
copyright: ''
googleAnalytics: ''
disqusShortname: ''
metaDataFormat: yaml
footnoteReturnLinkContents: '&#8617;'
pagination:
  pagerSize: 5
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
enableEmoji: true
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      hardwraps: false
      unsafe: true
  highlight:
    style: github
  tableOfContents:
    endLevel: 2
    ordered: false
    startLevel: 2
params:
  custom_theme: ''
  customheadingFontFamily: Baskerville
  customtextFontFamily: Commissioner
  description: A modern, beautiful, and easily configurable blog theme for Hugo.
  favicon: /img/homeicon.png
  headingFontFamily: sans-serif
  logo: /img/homeicon.png
  mainSections:
    - profiles
    - gallery
    - project
    - talk
    - pub
  math:
    renderer: katex
  navallcaps: true
  orgLocal: Anywhere
  orgName: RStudio
  sharing_image: /img/street-crop.jpg
  social:
    - icon: github
      icon_pack: fab
      url: https://github.com/lolosp
    - icon: bluesky
      icon_pack: fab
      url: https://bsky.app/profile/lspake.bsky.social
    - icon: orcid
      icon_pack: ai
      url: https://orcid.org/0000-0002-2243-7356
    - icon: researchgate
      icon_pack: fab
      url: https://www.researchgate.net/profile/Laure-Spake
    - icon: osf
      icon_pack: fab
      url: https://osf.io/z7hcm/
  socialInFooter: true
  socialInHeader: false
  textFontFamily: sans-serif
  theme: grayscale
  twitter: LSpake_Anthro
  utterances:
    issue_term: pathname
    label: 'comments :crystal_ball:'
    repo_name: lolosp/laurespake
    theme: boxy-light
    use_utterances: true
taxonomies:
  category: categories
  series: series
  tag: tags
menu:
  footer:
    - name: License
      title: License
      url: /license/
      weight: 1
    - name: Contributors
      title: Contributors
      url: /contributors/
      weight: 3
  header:
    - name: About Me 
      title: About Laure
      url: /about/
      weight: 1
    - name: The Lab
      title: About the lab and our team
      url: /lab/
      weight: 2
    - name: Projects
      title: Project Portfolio
      url: /project/
      weight: 3
    - name: Publications
      title: See our publications
      url: /pub/
      weight: 4
    - name: Teaching
      title: Materials for courses taught
      url: /course/
    - name: Gallery
      title: Glimpses into our work
      url: /gallery/
privacy:
  disqus:
    disable: false
  googleAnalytics:
    anonymizeIP: true
    disable: false
    respectDoNotTrack: true
  instagram:
    disable: false
    simple: true
  x:
    disable: false
    enableDNT: true
    simple: false
  vimeo:
    disable: false
    enableDNT: true
    simple: true
  youtube:
    disable: false
    privacyEnhanced: true
